export const foodData = {
  닭갈비: {
    country: "korean",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/chicken-ribs.png",
  },
  치킨: {
    country: "korean",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/chicken.png",
  },
  냉면: {
    country: "korean",
    amount: "properly",
    taste: "plain",
    score: 0,
    image: "src/assets/img/cold-noodle.png",
  },
  삼겹살: {
    country: "korean",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/chicken.png",
  },
  곱창: {
    country: "korean",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/chicken.png",
  },
  찜닭: {
    country: "korean",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/chicken.png",
  },
  족발: {
    country: "korean",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/pork-feet.png",
  },
  떡볶이: {
    country: "korean",
    amount: "simply",
    taste: "palin",
    score: 0,
    image: "src/assets/img/teokbokki.png",
  },
  양꼬치: {
    country: "asian",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/lamb-skewers.png",
  },
  마라탕: {
    country: "asian",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/maratang.png",
  },
  라멘: {
    country: "asian",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/ramen.png",
  },
  회: {
    country: "asian",
    amount: "largely",
    taste: "plain",
    score: 0,
    image: "src/assets/img/raw-fish.png",
  },
  연어덮밥: {
    country: "asian",
    amount: "properly",
    taste: "plain",
    score: 0,
    image: "src/assets/img/salmon-rice-bowl.png",
  },
  쌀국수: {
    country: "asian",
    amount: "simply",
    taste: "plain",
    score: 0,
    image: "src/assets/img/rice-noodle.png",
  },
  샤브샤브: {
    country: "asian",
    amount: "largely",
    taste: "plain",
    score: 0,
    image: "src/assets/img/raw-fish.png",
  },
  초밥: {
    country: "asian",
    amount: "properly",
    taste: "plain",
    score: 0,
    image: "src/assets/img/raw-fish.png",
  },
  돈가스: {
    country: "western",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/pork-cutlet.png",
  },
  스테이크: {
    country: "western",
    amount: "largely",
    taste: "fat",
    score: 0,
    image: "src/assets/img/steak.png",
  },
  샐러드: {
    country: "western",
    amount: "simply",
    taste: "plain",
    score: 0,
    image: "src/assets/img/salad.png",
  },
  샌드위치: {
    country: "western",
    amount: "simply",
    taste: "plain",
    score: 0,
    image: "src/assets/img/sandwich.png",
  },
  파스타: {
    country: "western",
    amount: "simply",
    taste: "plain",
    score: 0,
    image: "src/assets/img/pasta.png",
  },
  피자: {
    country: "western",
    amount: "properly",
    taste: "fat",
    score: 0,
    image: "src/assets/img/pizza.png",
  },
  햄버거: {
    country: "western",
    amount: "simply",
    taste: "fat",
    score: 0,
    image: "src/assets/img/hamburger.png",
  },
};

export const countryOptions = [
  { id: "korean", label: "한식" },
  { id: "western", label: "양식" },
  { id: "asian", label: "일/중식" },
];

export const amountOptions = [
  { id: "largely", label: "거하게" },
  { id: "properly", label: "적당하게" },
  { id: "simply", label: "간단하게" },
];

export const tasteOptions = [
  { id: "fat", label: "기름진 맛" },
  { id: "plain", label: "담백한 맛" },
];
