export const PAGE = {
  TYPE_SELECT: 0,
  START: 1,
  RECOMMEND_BY_TYPE_QUESTION_1: 2,
  RECOMMEND_BY_TYPE_QUESTION_2: 3,
  RECOMMEND_BY_TYPE_QUESTION_3: 4,
  RECOMMEND_BY_TYPE_RESULT: 5,
  RECOMMEND_BY_RANDOM: 6,
};
